import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  bg-gradient-to-t from-slate-950 to-slate-800 text-slate-200`}
      >
        <Navbar />
        <main className="flex min-h-screen flex-col justify-between p-4 sm:p-12">
          {children}
        </main>
      </body>
    </html>
  );
}
