name: Deploy Super Streaming to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t orhanma/super-streaming:latest .
          docker push orhanma/super-streaming:latest

      - name: Install SSH client
        run: sudo apt-get install -y ssh

      - name: Deploy to Digital Ocean Droplet
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
          DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}
        run: |
          echo "${{ secrets.DO_SSH_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa root@${{ secrets.DO_DROPLET_IP }} <<EOF
            docker pull orhanma/super-streaming:latest
            docker stop super-streaming || true
            docker rm super-streaming || true
            docker run -d --name super-streaming -p 80:3000 -e TMDB_API_KEY=${{ secrets.TMDB_API_KEY }} orhanma/super-streaming:latest
          EOF
